name: Binary builder

on:
  push:
    tags:
    - '*'

jobs:
  windows:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup environment
      run: |
        python -m pip install --upgrade pip setuptools wheel certifi
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller
        git checkout tags/v4.9
        cd bootloader
        python waf all
        cd ..
        pip install -e .
    - name: Build binary
      run: pyinstaller RainmeterAquasuite.spec
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: dist/RainmeterAquasuite.exe